/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bma_lua_javalib_LuaState_NativeData */

#ifndef _Included_bma_lua_javalib_LuaState_NativeData
#define _Included_bma_lua_javalib_LuaState_NativeData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
